### PR TITLE
Update 0-prepare-r-session-checkpoint-alternative.R

### PR DESCRIPTION
**Pull request by romanseidl**
The date was too early, when tricolore was not even released in CRAN. Works with this one.

### CODE REVIEW

**Comment by ikashnitsky** [comment]
Yeah, thanks for heads up. 
A major update of the reproducibility code is coming soon.

**Comment by romanseidl** [comment]
An update would be fine, I had two issues with the current versions of tricolore and ggtern:

   - in tricolore the "hexsrgb" field has been renamed (that's a non-issue)
   - "something" has changed with the lab arrows in ggtern, I didn't quite get it and then reverted everthing back to the old versions from 2018-05-28.

cheers,
roman

**Comment by ikashnitsky** [comment]
Thanks, Roman!

**Comment by romanseidl** [comment]
Just closing the request is not such a good idea, now nowbody will see the issue anymore.

It would have been good to either leave it open or to merge it.

**Comment by ikashnitsky** [comment]
I've moved to issues for now.

**Pull request closed without merging**
